# Generated by Django 5.0.2 on 2024-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
